riot:
  api:
    key: RGAPI-8f81a5fd-f3f8-49b7-8db2-2ea0c30227d0
    url:
      kr: https://kr.api.riotgames.com
      asia: https://asia.api.riotgames.com
      cdn: https://ddragon.leagueoflegends.com/cdn/
  versions: 13.16.1
logging:
  level:
    com:
      immersion:
        riot: DEBUG
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            dismiss404: true
            loggerLevel: FULL
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  data:
    redis:
      host: localhost
      port: 6379
cors:
  allow-methods : ['GET', 'POST', 'PUT', 'DELETE']
  allow-origins : ['http://localhost:3000']
